
// Shared dish data — the suggestion card pool used on Home, and the source list
// for the cache-warming route. Keeping this in one file means the app and the
// warming route can never drift out of sync with each other.

/* ── CONSTANTS ── */
export const SUGGESTIONS = ["Miso Glazed Salmon","Birria Tacos","Shakshuka","Mushroom Risotto","Korean BBQ Bowl","Coconut Curry Noodles","French Onion Soup","Smash Burgers"];
export type CardDef={title:string;desc:string;category:string;headerBg:string;catColor:string;textLight:boolean};
export const CARD_POOL: CardDef[] = [
  // ── SAFFRON ──────────────────────────────────────────────────────────
  {title:"Miso Glazed Salmon",        desc:"Umami glaze, lacquered and crispy",      category:"Staff Pick",        headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Birria Tacos",              desc:"Consommé dip, falling-apart beef",        category:"Weekend Project",   headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Coconut Curry Noodles",     desc:"Fragrant, creamy, hits every note",       category:"Comfort Food",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Chicken Tikka Masala",      desc:"The curry that won the world over",       category:"Comfort Food",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Truffle Pasta",             desc:"Simplicity at its most indulgent",        category:"Date Night",        headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Crab Cakes",                desc:"Golden crust, all lump crab inside",      category:"Staff Pick",        headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Pulled Pork Sliders",       desc:"Low, slow, and worth every minute",       category:"Weekend Project",   headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Lobster Bisque",            desc:"Velvety, restaurant-worthy, at home",     category:"Showstopper",       headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Duck Confit",               desc:"Crispy skin, silk beneath it",            category:"Weekend Project",   headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Beef Bulgogi",              desc:"Caramelised edges, sesame, scallion",     category:"Quick & Easy",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Chicken Shawarma",          desc:"Spiced, charred, wrapped in pita",        category:"Crowd Pleaser",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Mango Sticky Rice",         desc:"Coconut cream, ripe mango, pure joy",     category:"Dessert",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Smoked Brisket",            desc:"12-hour smoke, bark you can hear",        category:"Weekend Project",   headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Eggs Benedict",             desc:"Perfectly poached, hollandaise dream",    category:"Brunch",            headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Peach Burrata Salad",       desc:"Summer on a white plate",                 category:"Light & Fresh",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Butternut Squash Soup",     desc:"Velvety, warming, spiced just right",     category:"Seasonal",          headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Honey Garlic Shrimp",       desc:"Sweet, sticky, done in 15 minutes",       category:"Quick & Easy",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Baklava",                   desc:"Honey-soaked, 40 layers of flaky",        category:"Dessert",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Shakshuka",                 desc:"Eggs in spiced tomato, ready to tear",    category:"Brunch",            headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Lemon Herb Salmon",         desc:"Bright, flaky, endlessly effortless",     category:"Quick & Easy",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Chicken Pot Pie",           desc:"Golden lid, creamy filling underneath",   category:"Comfort Food",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Baked Brie",                desc:"Honey, walnuts, melted all the way",      category:"Staff Pick",        headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Shrimp Scampi",             desc:"Butter, white wine, lemon, garlic",       category:"Date Night",        headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Peking Duck",               desc:"Lacquered skin, hoisin, thin pancakes",   category:"Showstopper",       headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Beef Wellington",           desc:"Puff pastry perfection around tenderloin",category:"Showstopper",       headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Clam Chowder",              desc:"New England, thick, briny, satisfying",   category:"Comfort Food",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Lobster Rolls",             desc:"Maine-style, warm butter, brioche",        category:"Staff Pick",        headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Crème Caramel",             desc:"Silky custard, amber caramel crown",       category:"Dessert",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"French Dip Sandwich",       desc:"Slow-roasted beef, au jus for dipping",   category:"Crowd Pleaser",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Mango Lassi Chicken",       desc:"Yogurt-marinated, tenderised overnight",  category:"Date Night",        headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Potato Gratin",             desc:"Cream, gruyère, layered to the top",      category:"Comfort Food",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Steak Frites",              desc:"Bistro classic, herb butter, crispy fries",category:"Date Night",       headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Pork Belly Bao",            desc:"Fluffy buns, sticky pork, pickled veg",   category:"Crowd Pleaser",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Caramelised Onion Tart",    desc:"Sweet, jammy, buttery pastry shell",       category:"Brunch",            headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Lemon Tart",                desc:"Sharp, silky, shortcrust perfection",      category:"Dessert",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Chicken Marsala",           desc:"Mushrooms, fortified wine, pan sauce",    category:"Date Night",        headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Carnitas",                  desc:"Crispy-edged pork, orange and cumin",     category:"Weekend Project",   headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Prawn Cocktail",            desc:"Retro, iconic, still utterly delicious",  category:"Staff Pick",        headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Tarte Tatin",               desc:"Upside-down apple, buttery caramel",       category:"Dessert",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Cheese Soufflé",            desc:"Light as air, gruyère all the way through",category:"Showstopper",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Crispy Duck Salad",         desc:"Thai herbs, pomelo, toasted coconut",     category:"Light & Fresh",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Churros con Chocolate",     desc:"Crispy fried dough, thick drinking chocolate",category:"Dessert",       headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Pappardelle Bolognese",     desc:"Four-hour ragù, wide ribbons of pasta",   category:"Weekend Project",   headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Ginger Scallion Fish",      desc:"Steamed whole, silky ginger oil poured hot",category:"Staff Pick",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Patatas Bravas",            desc:"Crispy cubes, smoky sauce, aioli",         category:"Quick & Easy",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Croque Madame",             desc:"Grilled ham, béchamel, fried egg on top", category:"Brunch",            headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Mochi Ice Cream",           desc:"Chewy rice dough, cold filling within",   category:"Dessert",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Ceviche",                   desc:"Lime-cured fish, fresh and bright",        category:"Light & Fresh",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Chicken Piccata",           desc:"Lemon, capers, white wine pan sauce",     category:"Quick & Easy",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Moules Marinière",          desc:"White wine, shallots, mussels, bread",    category:"Staff Pick",        headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Banana Foster",             desc:"Caramelised bananas, rum, vanilla ice cream",category:"Dessert",        headerBg:"#F4A021",catColor:"#F4A021",textLight:false},

  // ── EMBER ────────────────────────────────────────────────────────────
  {title:"Smash Burgers",             desc:"Crispy-edged patties, secret sauce",      category:"Crowd Pleaser",     headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"French Onion Soup",         desc:"Gruyère lid, caramelised all the way",    category:"Comfort Food",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Nashville Hot Chicken",     desc:"Fiery crust, pickles, soft bun",          category:"Bold & Spicy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Beef Tacos",                desc:"Seasoned beef, every topping on it",      category:"Quick & Easy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Spaghetti Carbonara",       desc:"Silky egg sauce, crispy guanciale",       category:"Date Night",        headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Beef Short Ribs",           desc:"Braised until they fall off the bone",    category:"Weekend Project",   headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Ramen",                     desc:"Rich tonkotsu broth, soft-boiled egg",    category:"Weekend Project",   headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Chili Con Carne",           desc:"Smoky, deep, slow-simmered all day",      category:"Comfort Food",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Lamb Kofta",                desc:"Spiced and charred, tzatziki alongside",  category:"Crowd Pleaser",     headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Korean Fried Chicken",      desc:"Double-fried, sticky gochujang glaze",    category:"Bold & Spicy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"BBQ Ribs",                  desc:"Sticky glaze, smoke ring, clean bone",    category:"Weekend Project",   headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Shakshuka Verde",           desc:"Tomatillo, green chilli, fresh herbs",    category:"Bold & Spicy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Butter Chicken",            desc:"Silky, aromatic, everyone loves it",      category:"Comfort Food",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Beef Pho",                  desc:"Clear broth, star anise, rice noodles",   category:"Weekend Project",   headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Chorizo Hash",              desc:"Crispy potatoes, paprika, runny egg",     category:"Brunch",            headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Spicy Tuna Crispy Rice",    desc:"Restaurant-grade trick you can do at home",category:"Staff Pick",       headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Harissa Roast Chicken",     desc:"North African spice, crispy skin",        category:"Crowd Pleaser",     headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Szechuan Mapo Tofu",        desc:"Numbing, spicy, silky all at once",       category:"Bold & Spicy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Crème Brûlée",              desc:"Silky custard, the crackable sugar top",  category:"Date Night",        headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Shakshuka",                 desc:"Tomato, cumin, eggs poached right in",    category:"Brunch",            headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Mac and Cheese",            desc:"Three-cheese, béchamel, breadcrumb top",  category:"Comfort Food",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Chicken Parmesan",          desc:"Pounded, breaded, sauce, melted mozzarella",category:"Crowd Pleaser",   headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Brisket Tacos",             desc:"Smoked beef, salsa verde, cotija",        category:"Weekend Project",   headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Jerk Chicken",              desc:"Scotch bonnet heat, allspice, charred",   category:"Bold & Spicy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Beef Stroganoff",           desc:"Tender strips, sour cream, egg noodles",  category:"Comfort Food",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Lamb Shoulder",             desc:"7-hour roast, falls apart with a spoon",  category:"Weekend Project",   headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Crispy Pork Belly",         desc:"Crackling that shatters, melt within",    category:"Weekend Project",   headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Spicy Miso Ramen",          desc:"Chilli oil surface, corn, soft egg",      category:"Bold & Spicy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Sloppy Joes",               desc:"Messy, saucy, unapologetically good",     category:"Crowd Pleaser",     headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Boeuf Bourguignon",         desc:"Red wine, lardons, pearl onions",         category:"Weekend Project",   headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Enchiladas Rojas",          desc:"Rolled corn tortillas, red chile sauce",   category:"Crowd Pleaser",     headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Dry-Aged Ribeye",           desc:"Butter-basted, rosemary, pure luxury",    category:"Date Night",        headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Bang Bang Shrimp",          desc:"Crispy, creamy sauce, just a little heat",category:"Crowd Pleaser",     headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Goulash",                   desc:"Hungarian paprika stew, sour cream",      category:"Comfort Food",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Dan Dan Noodles",           desc:"Peanut, chilli oil, minced pork, sesame", category:"Bold & Spicy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Chicken and Waffles",       desc:"Crispy fried chicken, maple syrup drizzle",category:"Brunch",           headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Kimchi Jjigae",             desc:"Deeply fermented, pork, tofu, warming",   category:"Comfort Food",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Lamb Chops",                desc:"Herb-crusted, pan-seared, mint sauce",    category:"Date Night",        headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Shakshuka with Feta",       desc:"Creamy cheese crumbles into spiced sauce",category:"Brunch",            headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Buffalo Wings",             desc:"Sticky, spicy, bleu cheese on the side",  category:"Crowd Pleaser",     headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Lobster Thermidor",         desc:"French classic, cream, tarragon, shell",  category:"Showstopper",       headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Jollof Rice",               desc:"West African tomato rice, smoky bottom",  category:"Crowd Pleaser",     headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Chicken Tikka Skewers",     desc:"Charred yogurt-marinated, raita alongside",category:"Quick & Easy",     headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Pork Vindaloo",             desc:"Fiery Goan curry, vinegar heat",          category:"Bold & Spicy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Beef Rendang",              desc:"Malaysian slow-cooked, coconut, caramelised",category:"Weekend Project", headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Cheese Steak",              desc:"Shaved ribeye, provolone, soft hoagie",   category:"Crowd Pleaser",     headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Pernil",                    desc:"Puerto Rican pork shoulder, crispy skin",  category:"Weekend Project",   headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Grilled Octopus",           desc:"Charred, tender, lemon, olive oil",       category:"Staff Pick",        headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Spicy Lamb Flatbread",      desc:"Lahmacun — Turkey's answer to pizza",     category:"Bold & Spicy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Arroz con Pollo",           desc:"One pot, saffron rice, tender chicken",   category:"Comfort Food",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Chocolate Lava Cake",       desc:"Molten centre, pour it and watch",        category:"Dessert",           headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Chicken Souvlaki",          desc:"Marinated, grilled, pita, tzatziki",      category:"Quick & Easy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},

  // ── FOREST ───────────────────────────────────────────────────────────
  {title:"Mushroom Risotto",          desc:"Creamy, earthy, stirred with patience",   category:"Date Night",        headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Korean BBQ Bowl",           desc:"Gochujang beef, pickled everything",      category:"Bold & Spicy",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Pad Thai",                  desc:"Classic street noodles, tamarind pull",   category:"Quick & Easy",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Caesar Salad",              desc:"Anchovy dressing, house-made croutons",   category:"Quick & Easy",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Pesto Gnocchi",             desc:"Pillowy, herby, done before you know it", category:"Quick & Easy",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Niçoise Salad",             desc:"French bistro perfection, tuna and olives",category:"Light & Fresh",    headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Leek & Potato Soup",        desc:"Velvety, simple, deeply comforting",      category:"Comfort Food",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Prawn Linguine",            desc:"Garlic, chilli, white wine, done fast",   category:"Date Night",        headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Falafel Wraps",             desc:"Crispy chickpea, herby tahini, pita",     category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Wild Mushroom Toast",       desc:"Earthy, buttery, heaped on sourdough",    category:"Brunch",            headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Green Goddess Bowl",        desc:"Avocado dressing, grains, everything green",category:"Light & Fresh",   headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Osso Buco",                 desc:"Milanese braised veal, gremolata finish", category:"Showstopper",       headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Roasted Cauliflower",       desc:"Tahini, pomegranate seeds, za'atar",      category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Tiramisu",                  desc:"Espresso-soaked, cloud-like mascarpone",  category:"Dessert",           headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Hainanese Chicken Rice",    desc:"Silky poached, fragrant oily rice",       category:"Staff Pick",        headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Vegetable Wellington",      desc:"Golden pastry, hearty earthy filling",    category:"Showstopper",       headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Tom Kha Gai",               desc:"Thai coconut galangal soup, pure warmth", category:"Comfort Food",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Mole Negro",                desc:"The most complex sauce in existence",      category:"Weekend Project",   headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Bouillabaisse",             desc:"Marseille fish stew with rouille toast",  category:"Showstopper",       headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Avocado Toast",             desc:"The original and still the best",         category:"Brunch",            headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Lentil Dal",                desc:"Tempered spices, yellow lentils, ghee",   category:"Comfort Food",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Miso Soup",                 desc:"Dashi, tofu, wakame, utterly restorative",category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Grilled Corn Elote",        desc:"Charred, mayo, cotija, lime, chili",      category:"Crowd Pleaser",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Spanakopita",               desc:"Spinach, feta, 40 sheets of phyllo",      category:"Weekend Project",   headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Caprese Salad",             desc:"Tomato, mozzarella, basil, olive oil",    category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Mushroom Wellington",       desc:"Umami-packed, stunning on the table",     category:"Showstopper",       headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Beet & Goat Cheese Salad",  desc:"Earthy, creamy, walnuts for crunch",      category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Zucchini Fritters",         desc:"Golden, herb-flecked, yogurt to dip",     category:"Brunch",            headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Ribollita",                 desc:"Tuscan bread and bean soup, twice-cooked", category:"Comfort Food",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Saag Paneer",               desc:"Silky spinach, soft cubes of cheese",     category:"Comfort Food",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Okonomiyaki",               desc:"Japanese savoury pancake, everything in", category:"Crowd Pleaser",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Grilled Halloumi",          desc:"Squeaky, salty, charred and hot",         category:"Quick & Easy",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Cacio e Pepe",              desc:"Two ingredients, infinite technique",      category:"Date Night",        headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Tabouli",                   desc:"Parsley-forward, lemon, bulgur, mint",    category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Shakshuka Verde",           desc:"Tomatillo base, green chilli, fresh",     category:"Brunch",            headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Vegetarian Bibimbap",       desc:"Mixed rice bowl, gochujang, fried egg",   category:"Quick & Easy",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Gazpacho",                  desc:"Ice-cold Spanish tomato, pure summer",     category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Sweet Potato Curry",        desc:"Coconut milk, warming spices, vibrant",   category:"Comfort Food",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Pasta e Fagioli",           desc:"Roman peasant food at its finest",        category:"Comfort Food",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Smashed Cucumber Salad",    desc:"Garlic, chilli oil, sesame, refreshing",  category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Dosa",                      desc:"Fermented rice crêpe, sambar, chutneys",  category:"Brunch",            headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Fettuccine Alfredo",        desc:"Butter, parmesan, pasta water alchemy",   category:"Comfort Food",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Injera with Misir Wat",     desc:"Ethiopian sponge bread, spiced lentils",  category:"Staff Pick",        headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Roasted Tomato Soup",       desc:"Slow-roasted sweetness, basil oil",       category:"Comfort Food",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Chickpea Stew",             desc:"Moorish spices, spinach, lemon finish",   category:"Quick & Easy",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Stuffed Bell Peppers",      desc:"Herbed rice, roasted sweet pepper shell", category:"Crowd Pleaser",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Agedashi Tofu",             desc:"Crispy outside, silky within, dashi broth",category:"Staff Pick",       headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Fattoush",                  desc:"Levantine salad, crispy pita, sumac",     category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Panzanella",                desc:"Tuscan bread salad, ripe tomatoes",       category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Chana Masala",              desc:"Chickpeas in a deeply spiced tomato",     category:"Comfort Food",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Tempura Vegetables",        desc:"Impossibly light batter, dipping broth",  category:"Staff Pick",        headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},

  // ── BONUS ROUND — more Saffron ───────────────────────────────────────
  {title:"Pancakes",                  desc:"Thick, fluffy, maple syrup mandatory",    category:"Brunch",            headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Waffles",                   desc:"Crispy grid, butter pooled in every square",category:"Brunch",          headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Eggs Florentine",           desc:"Wilted spinach, poached egg, hollandaise",category:"Brunch",            headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Avocado Smash",             desc:"Charred sourdough, chilli flakes, lemon",  category:"Brunch",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"French Toast",              desc:"Brioche, vanilla custard, maple caramel",  category:"Brunch",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Huevos Rancheros",          desc:"Fried eggs, salsa roja, crispy tortilla",  category:"Brunch",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Smoked Salmon Bagel",       desc:"Everything bagel, cream cheese, capers",   category:"Brunch",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Biscuits and Gravy",        desc:"Flaky Southern biscuits, sausage gravy",   category:"Brunch",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Granola",                   desc:"Honey-toasted oats, coconut, dried fruit", category:"Brunch",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Breakfast Burritos",        desc:"Scrambled eggs, chorizo, salsa, folded",   category:"Brunch",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Monte Cristo Sandwich",     desc:"Fried, dusted with sugar, jam on side",    category:"Brunch",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Chilaquiles",               desc:"Fried tortillas, salsa, crema, cheese",    category:"Brunch",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Dutch Baby",                desc:"Puffed oven pancake, lemon and sugar",     category:"Brunch",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Smorgasbord Platter",       desc:"Gravlax, rye, pickles, Scandinavian spread",category:"Brunch",          headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Quiche Lorraine",           desc:"Buttery pastry, bacon, gruyère custard",   category:"Brunch",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  // American classics
  {title:"Meatloaf",                  desc:"Brown sugar glaze, the family favourite",  category:"Comfort Food",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Pot Roast",                 desc:"Tender beef, carrots, Sunday-dinner energy",category:"Comfort Food",    headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Clam Chowder Bread Bowl",   desc:"Sourdough bowl, creamy brine within",      category:"Comfort Food",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Grilled Cheese",            desc:"Three cheeses, buttered sourdough",        category:"Quick & Easy",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"BLT",                       desc:"Perfect bacon, ripe tomato, iceberg",      category:"Quick & Easy",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Club Sandwich",             desc:"Triple-decker, turkey, bacon, avocado",    category:"Quick & Easy",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Loaded Fries",              desc:"Cheese sauce, bacon, jalapeño, sour cream",category:"Crowd Pleaser",    headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Devilled Eggs",             desc:"Paprika-dusted, creamy filling, retro",    category:"Crowd Pleaser",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Cornbread",                 desc:"Cast iron, honey butter, golden crust",    category:"Comfort Food",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Chicken Noodle Soup",       desc:"The one you make when everything hurts",   category:"Comfort Food",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Tuna Melt",                 desc:"Open-faced, cheddar bubbled, broiled",     category:"Quick & Easy",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Coleslaw",                  desc:"Creamy, tangy, made from scratch",         category:"Quick & Easy",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Potato Salad",              desc:"Mustard, dill, perfectly chilled",         category:"Crowd Pleaser",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Apple Pie",                 desc:"Flaky double crust, cinnamon apple",       category:"Dessert",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Cheesecake",                desc:"New York style, dense, with sour cream top",category:"Dessert",         headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Banana Bread",              desc:"Ripe bananas, walnuts, chocolate optional",category:"Brunch",            headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Blueberry Muffins",         desc:"Domed top, bursting fruit, sugar crust",   category:"Brunch",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Peach Cobbler",             desc:"Juicy stone fruit, biscuit top, warm",     category:"Dessert",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Bread Pudding",             desc:"Brioche, bourbon sauce, vanilla custard",  category:"Dessert",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  // More international
  {title:"Lamb Tagine",               desc:"Moroccan slow-cook, apricot, ras el hanout",category:"Weekend Project", headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Paella Valenciana",         desc:"Saffron rice, socarrat, rabbit and beans", category:"Weekend Project",   headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Pho Bo",                    desc:"Vietnamese beef broth, star anise, herbs",  category:"Weekend Project",  headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Nasi Goreng",               desc:"Indonesian fried rice, kecap manis",       category:"Quick & Easy",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Pierogi",                   desc:"Polish dumplings, potato and cheese",       category:"Comfort Food",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Jerk Shrimp",               desc:"Scotch bonnet, allspice, char-grilled",    category:"Bold & Spicy",      headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Khao Man Gai",              desc:"Thai poached chicken, garlic rice, sauce",  category:"Staff Pick",       headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Sicilian Arancini",         desc:"Fried risotto balls, mozzarella core",      category:"Crowd Pleaser",    headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Laab",                      desc:"Minced meat salad, lime, toasted rice",     category:"Light & Fresh",    headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Poke Bowl",                 desc:"Ahi tuna, edamame, sesame, sushi rice",    category:"Light & Fresh",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Katsu Curry",               desc:"Crispy cutlet, Japanese curry sauce, rice", category:"Comfort Food",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Khachapuri",                desc:"Georgian cheese bread, egg yolk centre",   category:"Staff Pick",        headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Borscht",                   desc:"Ukrainian beetroot soup, sour cream",       category:"Seasonal",         headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Som Tum",                   desc:"Green papaya, chilli, peanuts, lime",       category:"Bold & Spicy",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Gado Gado",                 desc:"Indonesian peanut sauce salad with egg",   category:"Light & Fresh",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Shakshuka",                 desc:"North African, spiced, egg-poached glory",  category:"Brunch",           headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Ful Medames",               desc:"Egyptian fava beans, cumin, olive oil",    category:"Brunch",            headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Cassoulet",                 desc:"French duck, sausage, white bean braise",  category:"Weekend Project",   headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Pissaladière",              desc:"Provençal onion tart, anchovies, olives",  category:"Staff Pick",        headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Empanadas",                 desc:"Flaky pastry, seasoned beef, chimichurri", category:"Crowd Pleaser",     headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Arepas",                    desc:"Stuffed corn cakes, black beans, cheese",  category:"Brunch",            headerBg:"#F4A021",catColor:"#F4A021",textLight:false},
  {title:"Braised Short Rib Tacos",   desc:"Fall-apart beef, pickled onion, salsa",    category:"Weekend Project",   headerBg:"#F4A021",catColor:"#F4A021",textLight:false},

  // ── MORE EMBER ───────────────────────────────────────────────────────
  {title:"Tres Leches Cake",          desc:"Soaked in three milks, pillowy soft",      category:"Dessert",           headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Churro Waffles",            desc:"Cinnamon sugar, chocolate dipping sauce",  category:"Brunch",            headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Spare Ribs",                desc:"Dry rub, low oven, finish on the grill",   category:"Weekend Project",   headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Chilli Cheese Dog",         desc:"All-beef frank, chilli con carne, cheese", category:"Crowd Pleaser",     headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Pulled Chicken Sandwich",   desc:"Chipotle-smoked, pickled slaw, brioche",   category:"Crowd Pleaser",     headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Burnt Ends",                desc:"Brisket point, double-smoked, sticky",     category:"Weekend Project",   headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Al Pastor Tacos",           desc:"Pineapple-marinated pork, achiote",        category:"Bold & Spicy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Pollo a la Brasa",          desc:"Peruvian rotisserie chicken, ají verde",   category:"Crowd Pleaser",     headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Tteokbokki",                desc:"Korean rice cakes, gochujang, fishcakes",  category:"Bold & Spicy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Lamb Rogan Josh",           desc:"Kashmiri red curry, yogurt, deeply spiced",category:"Bold & Spicy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Chicken Fajitas",           desc:"Sizzling cast iron, peppers, warm tortilla",category:"Crowd Pleaser",    headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Pepperoni Pizza",           desc:"Cupped and crisp, fennel sausage too",     category:"Crowd Pleaser",     headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Pork Dumplings",            desc:"Pan-fried, ginger, black vinegar dip",     category:"Staff Pick",        headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Sfincione",                 desc:"Sicilian thick-crust pizza, onion, caciocavallo",category:"Weekend Project",headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Tonkatsu",                  desc:"Breaded pork cutlet, shredded cabbage",    category:"Comfort Food",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Chimichurri Steak",         desc:"Flank, herby green sauce, grilled hot",    category:"Date Night",        headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Suya",                      desc:"Nigerian spiced beef skewers, peanut crust",category:"Bold & Spicy",     headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Shabu Shabu",               desc:"Japanese hot pot, paper-thin beef, dashi", category:"Date Night",        headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Fried Chicken Sandwich",    desc:"Pickle-brined, crispy, stacked tall",      category:"Crowd Pleaser",     headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Cheeseburger",              desc:"Smash patty, American cheese, dill pickle",category:"Quick & Easy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Carne Asada",               desc:"Citrus-marinated, flame-kissed skirt steak",category:"Bold & Spicy",    headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Pasteles",                  desc:"Puerto Rican masa parcels, pork filling",  category:"Weekend Project",   headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Chicken Souvlaki Plate",    desc:"Grilled, pita, tzatziki, Greek salad",     category:"Quick & Easy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Dakgalbi",                  desc:"Korean spicy stir-fried chicken, rice cake",category:"Bold & Spicy",    headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Smoky Black Bean Soup",     desc:"Chipotle, cumin, lime, sour cream",        category:"Comfort Food",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Adobo Chicken",             desc:"Filipino vinegar-soy braise, bay leaf",    category:"Comfort Food",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Pork Schnitzel",            desc:"Viennese, thin-pounded, lemon and capers", category:"Quick & Easy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Bún Bò Huế",               desc:"Spicy Vietnamese beef and pork noodle",    category:"Bold & Spicy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Mutton Biryani",            desc:"Basmati, whole spices, saffron, dum-cooked",category:"Weekend Project",  headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Doubles",                   desc:"Trinidadian curried chickpea, fried bara", category:"Staff Pick",        headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Keema Matar",               desc:"Minced lamb, peas, ginger, tomato",        category:"Quick & Easy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Gyudon",                    desc:"Japanese beef and onion rice bowl",         category:"Quick & Easy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Chicken 65",                desc:"South Indian fried chicken, curry leaves", category:"Bold & Spicy",      headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Asado",                     desc:"Argentine grill, whole cuts, chimichurri", category:"Weekend Project",   headerBg:"#E8431A",catColor:"#E8431A",textLight:true},
  {title:"Chermoula Fish",            desc:"North African herb sauce, roasted whole",  category:"Staff Pick",        headerBg:"#E8431A",catColor:"#E8431A",textLight:true},

  // ── MORE FOREST ──────────────────────────────────────────────────────
  {title:"Fried Rice",                desc:"Wok-tossed, better than any takeout",      category:"Quick & Easy",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Minestrone",                desc:"Italian vegetable soup, parmesan rind",    category:"Comfort Food",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Prawn Tom Yum",             desc:"Hot and sour, lemongrass, kaffir lime",    category:"Bold & Spicy",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Baba Ganoush",              desc:"Charred aubergine, tahini, smoky",         category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Eggplant Parmesan",         desc:"Layered, sauced, molten mozzarella",       category:"Comfort Food",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Spinach Börek",             desc:"Flaky phyllo, feta and spinach filling",   category:"Crowd Pleaser",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Greek Lemon Chicken Soup",  desc:"Avgolemono — silky, lemony, restorative",  category:"Comfort Food",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Kale Caesar",               desc:"Massaged kale, anchovy dressing, crouton", category:"Light & Fresh",    headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Congee",                    desc:"Chinese rice porridge, ginger, sesame oil",category:"Comfort Food",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Shakshuka Blanca",          desc:"White shakshuka, za'atar, labneh",         category:"Brunch",            headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Corn Chowder",              desc:"Sweet corn, bacon, cream, chive oil",      category:"Seasonal",          headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Mujaddara",                 desc:"Lentils and rice, crispy onion heap",      category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Jackfruit Tacos",           desc:"Pulled texture, smoky spice, fresh salsa", category:"Crowd Pleaser",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Cauliflower Steak",         desc:"Roasted whole, harissa, yogurt, almonds",  category:"Date Night",        headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Lentil Soup",               desc:"Red lentils, cumin-tempered, lemon",       category:"Comfort Food",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Watermelon Feta Salad",     desc:"Summer's best flavour combination",        category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Acai Bowl",                 desc:"Frozen blended, granola, honey, fruit",    category:"Brunch",            headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Veggie Bibimbap",           desc:"Stone pot, seasonal vegetables, gochujang",category:"Quick & Easy",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Spring Rolls",              desc:"Fresh rice paper, shrimp, herbs, dip",    category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Roasted Root Veg",          desc:"Honey-glazed, thyme, sherry vinegar",      category:"Seasonal",         headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Mushroom Udon",             desc:"Thick noodles, dashi, king oyster",        category:"Comfort Food",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Squash Ravioli",            desc:"Brown butter, sage, amaretto crumbs",      category:"Date Night",        headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Waldorf Salad",             desc:"Apple, walnut, celery, creamy dressing",   category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Lentil Bolognese",          desc:"Umami-rich, red wine, pappardelle",        category:"Comfort Food",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Grilled Asparagus",         desc:"Lemon oil, flaked salt, parmesan shavings",category:"Light & Fresh",    headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Tofu Katsu Curry",          desc:"Crispy tofu, Japanese curry sauce",        category:"Comfort Food",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Roasted Beet Hummus",       desc:"Vivid pink, tahini, olive oil, pita",      category:"Staff Pick",        headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Spinach Artichoke Dip",     desc:"Baked, cheesy, pull-apart bread alongside",category:"Crowd Pleaser",    headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Black Bean Quesadillas",    desc:"Crispy, gooey, salsa verde on the side",   category:"Quick & Easy",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Carrot Ginger Soup",        desc:"Smooth, warming, coconut cream swirl",     category:"Seasonal",         headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Muhammara",                 desc:"Roasted red pepper walnut dip, pomegranate",category:"Staff Pick",       headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Pea and Mint Soup",         desc:"Bright, verdant, crème fraîche",           category:"Light & Fresh",    headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Thai Basil Fried Rice",     desc:"Wok hei, holy basil, fried egg on top",   category:"Quick & Easy",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Frittata",                  desc:"Oven-finished, zucchini, goat cheese",     category:"Brunch",            headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Mushroom Stroganoff",       desc:"Creamy, earthy, egg noodles underneath",   category:"Comfort Food",      headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Olive Tapenade Bruschetta", desc:"Black olives, capers, crusty bread",       category:"Staff Pick",        headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Zucchini Pasta",            desc:"Spiralised, garlic oil, cherry tomatoes",  category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Soba Noodle Salad",         desc:"Cold buckwheat, sesame, cucumber, scallion",category:"Light & Fresh",   headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Curried Lentil Bowl",       desc:"Warming, coconut, fried shallots on top",  category:"Comfort Food",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Raw Pad Thai",              desc:"Courgette noodles, peanut, lime, herb",    category:"Light & Fresh",     headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Hazelnut Chocolate Tart",   desc:"Silky ganache, praline, shortcrust",       category:"Dessert",           headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Panna Cotta",               desc:"Vanilla, barely set, berry coulis",        category:"Dessert",           headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Financiers",                desc:"Brown butter almond cakes, golden",        category:"Dessert",           headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Earl Grey Poached Pears",   desc:"Delicate, floral, served with cream",      category:"Dessert",           headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Cardamom Rice Pudding",     desc:"Slow-cooked, rose water, pistachio",       category:"Dessert",           headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Pavlova",                   desc:"Crisp meringue, cream, summer fruits",     category:"Dessert",           headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Profiteroles",              desc:"Choux, crème pâtissière, chocolate",        category:"Dessert",           headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Sticky Toffee Pudding",     desc:"Date sponge, butterscotch sauce, warm",    category:"Dessert",           headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Île Flottante",             desc:"Floating meringue, crème anglaise, praline",category:"Dessert",          headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Galette des Rois",          desc:"Frangipane puff pastry, buttery layers",   category:"Dessert",           headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
  {title:"Japanese Cheesecake",       desc:"Souffle-light, jiggly, barely sweet",      category:"Dessert",           headerBg:"#1E3A2F",catColor:"#1E3A2F",textLight:true},
];
// Flat, de-duplicated list of every dish title in the pool — this is what the
// warming route iterates over. A few titles intentionally repeat above
// (different categories), so this collapses them to one entry each.
export const DISH_TITLES: string[] = Array.from(new Set(CARD_POOL.map(c => c.title)));
